### ISSUE TITLE
version 11

### ISSUE THREAD

**Issue by Theopholis** [manuel-hegner/foundry-filepicker-favorites#106]
Just tried to download the latest version for V.11.301. I'm getting an error when trying to install.

Error: invalid comment length. expected: 2. found: 0
    at C:\Program Files\Foundry Virtual Tabletop\resources\app\node_modules\yauzl\index.js:133:25
    at C:\Program Files\Foundry Virtual Tabletop\resources\app\node_modules\yauzl\index.js:631:5
    at C:\Program Files\Foundry Virtual Tabletop\resources\app\node_modules\fd-slicer\index.js:32:7
    at FSReqCallback.wrapper [as oncomplete] (node:fs:681:5)

**Comment by r-valyar** [comment]
I confirm, the module cannot be installed on v11 of Foundry.

**Comment by manuel-hegner** [comment]
Could you try again? It seems the zip file was corrupted.

**Comment by r-valyar** [comment]
I confirm, installed & green on v11.301 :) Thanks!!!!

![image](https://github.com/manuel-hegner/foundry-filepicker-favorites/assets/63558984/6acd3ef8-ed86-438e-8728-f44a18805b7e)
