### ISSUE TITLE
Bad name display when blank space in folder name

### ISSUE THREAD

**Issue by Ghorin46** [manuel-hegner/foundry-filepicker-favorites#107]
When I create a favorite for a folder which name contains blank space, then the favorite name replaces the blank space by special caracter as you may see in below screenshot (the name "Campagne des Vestiges du Nord" is replaced by "Campagne%20des%20Vestiges%20du%20Nord"). Note : the favorite works fine but its display is very bad

![image](https://github.com/manuel-hegner/foundry-filepicker-favorites/assets/26152830/9878ba5b-1258-4822-bb4b-55ddc5bcd88d)

**Comment by manuel-hegner** [comment]
This is a foundry core issue and has nothing to do with this module.
