### ISSUE TITLE
Foundry V12 compatibility

### ISSUE THREAD

**Issue by SebastianH17** [manuel-hegner/foundry-filepicker-favorites#109]
Your wonderful module seems to have issues with Foundry's V12, the shortcuts still work, but the search gives an error message:

![image](https://github.com/manuel-hegner/foundry-filepicker-favorites/assets/84858570/20391d78-4e8d-4564-9e25-65aaa5ae3cd8)

Tested on the current beta version of PF2 and the current stable version of Foundry V12.325

**Comment by manuel-hegner** [comment]
New version with v12 compatibility released.
