### ISSUE TITLE
v12: Exception 

### ISSUE THREAD

**Issue by manituan** [manuel-hegner/foundry-filepicker-favorites#110]
when opening scene
![image](https://github.com/manuel-hegner/foundry-filepicker-favorites/assets/812457/6f6612fa-c181-4ca4-a647-85a029b5414c)

When searching for files
![image](https://github.com/manuel-hegner/foundry-filepicker-favorites/assets/812457/054edbc2-a25f-415c-9651-2f3c45e2d30f)

**Comment by manuel-hegner** [comment]
With which version did that happen?

**Comment by manituan** [comment]
1.2.5
And latest Foundry v12

I updated all the modules. But I have 1.2.5, whereas you have 1.7 available in github. 
Also, it shows that 1.2.5 is v12 compatible. If that helps.

**Comment by manuel-hegner** [comment]
The current version is 1.7.0. It should support v12

**Comment by manituan** [comment]
But it doesn't update to 1.7 from within Foundry. I guess I'll remove the module and reinstall it.

**Comment by manituan** [comment]
oh, I see what happened. At some point I locked it, can't remember why, and it hasn't been updated since. Sorry to bother you. All good!

**Comment by manuel-hegner** [comment]
No problem
