### ISSUE TITLE
Error on Load

### ISSUE THREAD

**Issue by brunocalado** [manuel-hegner/foundry-filepicker-favorites#111]
When the world starts there is a error message that show up

![image](https://github.com/manuel-hegner/foundry-filepicker-favorites/assets/4999783/849f72ac-3618-4147-8f3f-bfbbfaa3fa3b)

![image](https://github.com/manuel-hegner/foundry-filepicker-favorites/assets/4999783/51b7311d-d746-4b7c-8f74-cf7c3a79ce4b)

![image](https://github.com/manuel-hegner/foundry-filepicker-favorites/assets/4999783/23822463-8fc6-4e4b-8d03-7ed671c0b055)

**Comment by manuel-hegner** [comment]
Is this with the current version 1.7.0?

**Comment by brunocalado** [comment]
> Is this with the current version 1.7.0?

Update fixed. thank you
