### ISSUE TITLE
Players getting access to hidden folders

### ISSUE THREAD

**Issue by Gurrgel** [manuel-hegner/foundry-filepicker-favorites#34]
Found this out from one of my players yesterday, but it seems as if clicking a shortcut/favourite lets a player access a folder, even if that folder is normally hidden for players. It would be great if that didn't happen, since I would like to have my current story's folder with relevant assets as one of my favourites. If that's a hard thing to do, perhaps an option to simply disable the favourites for players would be a possible?

**Comment by manuel-hegner** [comment]
Mhhh, that is of course a problem. I will look into mitigating that.

**Comment by manuel-hegner** [comment]
Can you try if version 1.2.2 fixes this. 

A caveat is that the module decides which folders to search through during the page load. That means if you hide folders while players are online (or unhide them) this will not change the search results of the players until they reload.

**Comment by Gurrgel** [comment]
It's almost solved now, but not quite all the way. With the updated version a player still seems able to access the folder when I have it set as hidden. Trying to access any subfolders gives them an error message about not having access to the destination so it stops there, but they can still clearly see images in the root favourite folder, and they can also see the names of any subfolders, which could be revealing if, like me, you have a folder for each point of interest relevant to the current story, and the players may not necessarily have found them all yet.

**Comment by manuel-hegner** [comment]
Okay. I finally had time to work on this. I hope in version 1.2.3 that I thought of every edge case. Favorite buttons should now not be visible for players that are not allowed to access them.

**Comment by Gurrgel** [comment]
Sorry to be a bother again, but I don't see the effects you mention after upgrading Filepicker Improvements to version 1.2.3, and with Foundry Version 9.269). When I tried it right now logging in as a player from my browser, they were still able to see a new favorite folder that I set up (and then reloaded the server / logged in again) despite the folder being hidden, and them being unable to see said folder if they click the other favorite butten to reach the folder above the new one I just added. Apart from being given a few warnings, they also seem to be able to fully interact with said folder and its content as if it wasn't hidden. I managed to change the portrait for the player's character with an image from said folder for instance, and that worked, with the only issue being that I got a warning when I clicked the portrait again to change it back.

If that's of any help for clarifying what I'm seeing, I have a folder called **Stories**, and then a subfolder called **Story 7**, for the adventure we're currently playing. I currently have the **Stories** folder as a favorite, and when a player clicks that, they don't see the **Story 7** subfolder, which is hidden. However, if I instead add the **Story 7** folder as a favorite, they see and can interact with that folder and all its contencts without any issues, since I haven't separately hidden any of the subfolders in the **Story 7** folder. Let me know if you need any further information!

**Comment by manuel-hegner** [comment]
I suspect this is related to the rights of the players. If I try to recreate your scenario it works as expected. For me foundry makes it impossible for users to even request the files within hidden folders. Could you maybe post permission configurations and what permission level your users have?

**Comment by Gurrgel** [comment]
Here you go, don't think anything should be too much out of the ordinary, but please let me know if it differs from your settings in any relevant ways and I can play around with those settings a bit and see if it helps!
![image](https://user-images.githubusercontent.com/99760890/169715846-da275869-05a3-414b-8db7-9488d46b3bad.png)
![image](https://user-images.githubusercontent.com/99760890/169715862-717f9597-5888-4f73-910d-f4ef6106b342.png)
![image](https://user-images.githubusercontent.com/99760890/169715874-f03e3929-03c6-4f54-bc86-d2c6e6504c55.png)

**Comment by manuel-hegner** [comment]
I still can not reproduce the behaviour. If I set up folders like you say Foundry rejects access to the user to "Story 7" and all of its subfolders. This seems to be a very special case. To analyze this further I would need user access to a minimal (no other module) to look at the problem directly.
