### ISSUE TITLE
Proper syntax of S3 URL for shortcuts?

### ISSUE THREAD

**Issue by tbrockwood** [manuel-hegner/foundry-filepicker-favorites#54]
I'm trying to set up shortcuts to my S3 storage bucket, and I've chosen S3 as the source, but whatever format of bucket info I input, it says there's nothing there. A url I've tried, for ex. - (obviously replacing NameofMyBucket with the real name of it)
s3:fNameofmyBucket:fantasy/tokens/  

I've also tried removing the S3: part

**Comment by manuel-hegner** [comment]
Have you looked at how the image path looks when you just add edit a tile/token? As I am not using S3 I can't really confirm myself if this is a problem within the module or if you just need the correct path.

**Comment by tbrockwood** [comment]
Sorry, this can be closed, I figured it out.
