### ISSUE TITLE
Compatibility Warnings in the console

### ISSUE THREAD

**Issue by yjeroen** [manuel-hegner/foundry-filepicker-favorites#78]
![image](https://user-images.githubusercontent.com/1303988/200178669-c2d6c89f-d287-4285-9cc9-23eaf1b06d67.png)

**Comment by esheyw** [comment]
This is down to one of two modules throwing these for me, my OCD would love a quick patch to modernize the manifest. please? ❤

**Comment by WrexBG** [comment]
I've made a Pull Request to help fix this. It's some deprecated entries in the module.json that cause it so if you don't want to wait you can also fix them up yourself by editing the file or copying what I changed.
The PR is:
* #84

**Comment by manuel-hegner** [comment]
Thanks for the contribution. Should be fixed in 1.3.0
