### ISSUE TITLE
When I search nothing happens

### ISSUE THREAD

**Issue by YenBenGrey** [manuel-hegner/foundry-filepicker-favorites#92]
When I click on search, and then write a word in the box, then press enter, the line cursor goes back to the start of the word, the original picture is in the file selected box and no search results come up. 

I have done Find the Culprit which isn't helping as it just keeps saying Filepicker Improvements is the problem.

**Comment by manuel-hegner** [comment]
Currently there is no folder set in the "include folders" list. You have to add one in the settings. Does this solve it?

**Comment by lucaspicerni** [comment]
Solved it for me, thank you very much!
